version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/csv:/csv
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
